apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: capstone
  name: capstone-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - image: halzamly/springbootdemo
        name: capstone
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  labels:
    app: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80